#server:
#  port: 8888
#spring:
#  main:
#    allow-bean-definition-overriding: true
# application:
#    name: gateway-service

#  cloud:
#   discovery:
#    enabled: true
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path= /customers/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path= /products/**
